# Generated by Django 3.1.7 on 2021-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_using_genetic', '0003_auto_20210304_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_numb_students',
            field=models.IntegerField(default=0),
        ),
    ]
